terraform:
  -  'terraform/**'

app:
  - any: ['**', '!terraform/*', '!version.txt', '!README.md', '!CHANGELOG.md']

labeler:
  -  '.github/labeler.yml'

labeler2:
  -  '.github/*'

workflow_change:
  -  '.github/**'

anything:
  -  '**'
