name: Deploy

on:
  release:
    types: [released]

jobs:
  deploy:
    name: deploy-terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR labels
        id: pr_labels
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$GITHUB_REPOSITORY/pulls?state=all | jq '.[0].labels[].name'
          label_list_string=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$GITHUB_REPOSITORY/pulls?state=all | jq '.[0].labels[].name')
          echo $label_list_string

          if echo "$label_list_string" | grep -q '"app"'; then
              echo "It has the app-label"
              echo "is_app_release=true" >> $GITHUB_OUTPUT
          else
              echo "It doesn't have the app-label"
              echo "is_app_release=false" >> $GITHUB_OUTPUT
          fi

          if echo "$label_list_string" | grep -q '"terraform"'; then
              echo "It has the terraform-label"
              echo "is_terraform_release=true" >> $GITHUB_OUTPUT
          else
              echo "It doesn't have the terraform-label"
              echo "is_terraform_release=false" >> $GITHUB_OUTPUT
          fi

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Terraform
        if: steps.pr_labels.outputs.is_app_release == 'true'
        run: echo "Deploying Terraform..."
      
      - name: Deploy app
        if: steps.pr_labels.outputs.is_terraform_release == 'true'
        run: echo "Deploying app..."

