name: Deploy

on:
  release:
    types: [released]

jobs:
  deploy-terraform:
    name: deploy-terraform
    if: contains(github.ref, 'terraform')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR labels
        id: pr_labels
        run: |
          PR_NUMBER=$(gh api repos/$GITHUB_REPOSITORY/pulls --jq ".[] | select(.merge_commit_sha==\"${{ github.event.release.target_commitish }}\") | .number")
          echo $PR_NUMBER
          LABELS=$(gh api repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/labels --jq ".[].name")
          echo $LABELS
          echo "::set-output name=labels::${LABELS}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Terraform
        if: contains(steps.pr_labels.outputs.labels, 'terraform')
        run: echo "Deploying Terraform..."
      
      - name: Deploy app
        if: contains(steps.pr_labels.outputs.labels, 'app')
        run: echo "Deploying app..."

  #     - name: Deploy Other
  #       run: echo "Deploying app..."
