name: Release management app

on:
  push:
    branches:
      - master
    # paths:
    #   -  '**'
    #   -  '!terraform/*'
    # paths-ignore:
    #   - 'terraform/**'

jobs:
  release-management:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Manage release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ME_BOT_TOKEN }}
          release-type: simple
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}, {"type":"refactor","section":"Miscellaneous","hidden":false}]'
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get PR number
        id: pr_number 
        run: |
         bash .github/workflows/get_pr_number.sh ${{ steps.release.outputs.pr }}

      - name: Path filters
        uses: dorny/paths-filter@v2
        id: path_filters
        with:
          filters: |
            all:
              - '**'
            terraform:
              - 'terraform/**'

      - name: print_path_filters
        run: |
          echo ${{ steps.path_filters.outputs.all_count }}
          echo ${{ steps.path_filters.outputs.terraform_count }}
          a=${{ steps.path_filters.outputs.all_count }}-${{ steps.path_filters.outputs.terraform_count }}
          echo $a

      - name: all is larger
        if: steps.path_filters.outputs.all_count > steps.path_filters.outputs.terraform_count
        run: |
          echo "all is larger"

      - name: terraform is larger
        if: steps.path_filters.outputs.all_count < steps.path_filters.outputs.terraform_count
        run: |
          echo "terraform is larger"

      - name: app_something
        if: steps.path_filters.outputs.all == 'true'
        run: |
          echo "app-type"

      - name: terraform_something
        if: steps.path_filters.outputs.terraform == 'true'
        run: |
          echo "terraform-type"

      - name: app_something
        if: steps.path_filters.outputs.all == 'true' && steps.filter.outputs.terraform == 'true'
        run: |
          echo "both-type"      

      - name: Add_label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ steps.pr_number.outputs.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["app"]
            })
