name: Release management app

on:
  push:
    branches:
      - master
    paths:
      -  '**'
      -  '!terraform/*'
    # paths-ignore:
    #   - 'terraform/**'

jobs:
  release-management:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Manage release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ME_BOT_TOKEN }}
          release-type: simple
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}, {"type":"refactor","section":"Miscellaneous","hidden":false}]'
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get PR number
        id: pr_number 
        run: |
         bash .github/workflows/get_pr_number.sh ${{ steps.release.outputs.pr }}

      - name: Add_label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ steps.pr_number.outputs.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["app"]
            })
          #   fi
          # done
