name: Release management app

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'terraform/**'

jobs:
  release-management:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Manage release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ME_BOT_TOKEN }}
          release-type: simple
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}, {"type":"refactor","section":"Miscellaneous","hidden":false}]'
      
      - name: Get PR number
        id: pr_number 
        run: |
          PR_JSON="${{ steps.release.outputs.pr }}"
          echo "start PR_JSON"
          echo "${{ steps.release.outputs.pr }}"
          echo "end PR_JSON"
          echo "${PR_JSON}"

      
      - name: Labeler
        uses: actions/labeler@v4
        with:
          dot: true
          pr-number: ${{ steps.pr_number.outputs.number }}
      
      - name: Did labeler do anything
        run: |
          echo "printing new-labels"
          echo ${{ steps.Labeler.outputs.new-labels }}
          echo "printing all-labels"
          echo ${{ steps.Labeler.outputs.all-labels }}

          
      # PR_JSON="${{ steps.release.outputs.pr }}"
      # echo "PR_JSON start"
      # echo $PR_JSON
      # echo "PR_JSON end"
      # PR_NUMBER=$(jq -r '.number' <<< "$PR_JSON")
      # echo "::set-output name=number::$PR_NUMBER"

      
      # - name: Is release created
      #   if: ${{ steps.release.outputs.releases_created }}
      #   run: echo "release is created"
      # - name: Is release not created
      #   if: ${{ steps.release.outputs.releases_created == false}}
      #   run: echo "release is not created"
      # - name: Add app tag to release
      #   run: |
      #     for i in {1..5}
      #       do
      #         echo "writing the value ${i}:"
      #         echo "${{steps.release.outputs.releases_created}}"
      #         echo ${{steps.release.outputs.releases_created}}
      #         if [${{ steps.release.outputs.releases_created }}]
      #         then
      #           echo "it is true in the boolean sense"
      #         else
      #           echo "it is not true in the boolean sense"
      #         fi

      #         if [${{ steps.release.outputs.releases_created }}=="true"]
      #         then
      #           echo "it is true in the string sense"
      #         else
      #           echo "it is not true in the string sense"
      #         fi
      #         sleep 5
      #       done
          # for i in {1..10}
          # do
          #   if [[ "${{ steps.release.outputs.release_created }}" == "true" ]]; then
          #     git tag app ${{ steps.release.outputs.tag_name }}
          #     git push origin app
          #     echo "Release tagged"
          #     break
          #   else
          #     echo "Release not created yet, retrying in 5 seconds..."
          #     sleep 5
          #   fi
          # done
