name: Release management app

on:
  push:
    branches:
      - master

jobs:
  release-management:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Manage release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.ME_BOT_TOKEN }}
          release-type: simple
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}, {"type":"refactor","section":"Miscellaneous","hidden":false}]'
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get PR number
        id: pr_number 
        run: |
         bash .github/workflows/get_pr_number.sh ${{ steps.release.outputs.pr }}

      - name: Path filters
        uses: dorny/paths-filter@v2
        id: path_filters
        with:
          filters: |
            all:
              - '**'
            terraform:
              - 'terraform/**'
              - '.github/**'
            app-ignore-list:
              - 'CHANGELOG.md'
              - 'README.md'
              - 'version.txt'
              - 'terraform/**'

      - name: Label as app
        if: steps.path_filters.outputs.all_count > steps.path_filters.outputs.app-ignore-list_count #If there are any changes that ar not on the ignore list
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ steps.pr_number.outputs.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["app"]
            })

      - name: Label as terraform
        if: steps.path_filters.outputs.terraform == 'true' #If there are any terraform or deployment changes
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ steps.pr_number.outputs.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["app"]
            })
          debug: true
          retries: 5
